server:
  port: 8080
  servlet:
    context-path: /drumify

spring:
  application:
    name: Drumify
  datasource:
    url: jdbc:mysql://localhost:3307/drumify_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8280/realms/drumify-dev

idp:
  url: http://localhost:8280
  client-id: linhdev_drumify_app_BE
  client-secret: 9YtXpSTAfzdiJ1DQ2cQMN8sTR53IvVak

app:
  sync-secret: DrumifySyncSecret2026
ghn:
  url: https://dev-online-gateway.ghn.vn
  token-api: ad4c178c-8fc0-11f0-bdaf-ae7fa045a771
  shop-id: 199931